# Generated by Django 3.2 on 2021-05-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_core_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
